### ISSUE TITLE
ScheduleWithCron gives unexpected results with WithLocation

### ISSUE THREAD

**Issue by RonniSkansing** [procyon-projects/chrono#17]
**Description**
Using `ScheduleWithCron` with a `WithLocation` yield incorrect and unexpected results.

The easiest way to reproduce and understand the issue is to run the _Playground POC_ .

Notice the code works as expected when not using `WithLocation` 

**Expected behavior**
A cron to run every 2nd second.

**Behavior**
A cron can depending on location not run at all or run many times in a second.

**Playground POC**
https://go.dev/play/p/eGP1vQ-oKBE

Notice how `test2 ` is never output.
Try replacing `Europe/Copenhagen`  with `America/New_York` it will now runs many times in a second.

**Local POC**
```
package main

import (
      "context"
      "log"
      "time"

      "github.com/procyon-projects/chrono"
)

func main() {
      r := chrono.NewDefaultTaskScheduler()
      task := func(ctx context.Context) {
            log.Println("task run")
      }
      _, err := r.ScheduleWithCron(task, "*/2 * * * * *", chrono.WithLocation("Europe/Copenhagen")) // America/New_York
      if err != nil {
            log.Fatal(err)
      }
}
```

**Temp fix**
Remove `WithLocation` and calculate the offset yourself.

**Related bugs**
This could be related to:
https://github.com/procyon-projects/chrono/issues/15

**Comment by burakkoken** [comment]
Hi @RonniSkansing, thank you for letting me know about the issue.

This should be fixed with release v1.1.1. Can you please verify that the issue does not occur anymore?

@peatle-mibt can you also verify that the issue #15 has been resolved with this fix? 

Bug fix was a bit late because I'm working on multiple open source projects at the same time.
Sorry for that. @peatle-mibt

**Comment by RonniSkansing** [comment]
Hi @burakkoken 

Thanks for looking into it. 

With __v1.1.1__ I can still reproduce the bug.

Here is a playground POC:
https://go.dev/play/p/f8JCQ_Lfd_w

Running this locally also gives a unexpected results similar to the playground:
```
2022/09/28 08:24:04 America/New_York task run
2022/09/28 08:24:04 America/New_York task run
2022/09/28 08:24:04 America/New_York task run
2022/09/28 08:24:04 America/New_York task run
2022/09/28 08:24:04 America/New_York task run
...
```

The output of `go mod graph | grep chrono` returns `github.com/ronniskansing/test github.com/procyon-projects/chrono@v1.1.1`

**Comment by burakkoken** [comment]
Hi @RonniSkansing,

I had published **release v1.1.1** twice yesterday. I don’t know the reason why go does not download the latest code for **v1.1.1.**  It might be an issue with go module cache. Because I had deleted all resources belonging to **v1.1.1 tag.** 

I just created a **new release version v1.1.2**. There is no changes in code.
When I tried to run your code snippet in my local, it looks like everything is fine.

can you please also confirm that the issue has been resolved with **release v1.1.2**
